name: Release lib-version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
      
      - name: Extract version from Git tag
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Write version.py for VersionUtil
        run: |
          mkdir -p lib_version
          cat > lib_version/version.py <<EOF
          __version__ = "${VERSION}"
          EOF

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build & publish tools
        run: |
          pip install --upgrade pip
          pip install build wheel twine setuptools_scm

      - name: Build package
        run: python -m build
      
      - name: List dist for debugging
        run: ls -l dist

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: dist/*
          generateReleaseNotes: true